
name: swift-test

on: [push]
jobs:
  test:
    name: Test
    runs-on: macos-13
    timeout-minutes: 15
    strategy:
        matrix:
          destination: ['platform=macOS']
          testDestination: ['platform=macOS,arch=x86_64']
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.3.app

      - name: Build
        run: |
          xcodebuild clean build -project EssentialFeed.xcodeproj -scheme EssentialFeed -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project EssentialFeed.xcodeproj -scheme EssentialFeed -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.testDestination }}
